name: Testing kmc-lotto

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          mkdir -p $HOME/.local

      - name: configure
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/.local ..

      - name: install
        shell: bash
        run: |
          cd build
          make install

      - name: configure tests
        shell: bash
        run: |
          mkdir build_tests
          cd build_tests
          cmake -DCMAKE_BUILD_TYPE=Release -DKMCLOTTO_PREFIX=$HOME/.local ../tests

      - name: make tests
        shell: bash
        run: |
          cd build_tests
          make -j4 VERBOSE=1

      - name: run tests
        shell: bash
        run: |
          cd build_tests
          make test

      - name: upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kmc-lotto-test-log
          path: build_tests/Testing/Temporary/LastTest.log
